services:
  - type: web
    name: giftmate-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:application --workers 3 --bind 0.0.0.0:$PORT"
