# Generated by Django 5.1.6 on 2025-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_profile_birthday_profile_interests_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='gift',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
