# Generated by Django 5.1.6 on 2025-12-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на подарунок'),
        ),
    ]
