# Generated by Django 5.1.6 on 2026-01-16 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_gift_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Фото для story', upload_to='stories/')),
                ('title', models.CharField(blank=True, help_text='Заголовок/текст для story', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Опис', max_length=500)),
                ('background_color', models.CharField(default='#6366f1', help_text='Колір фону (hex)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(blank=True, help_text='Посилання на подарунок', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='gifts.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
