# Generated by Django 5.1.6 on 2025-12-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на подарунок'),
        ),
    ]
