# Generated by Django 5.1.6 on 2025-12-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_gift_remove_message_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gift',
        ),
    ]
